# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_detection/protos/class_predictor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import object_detection.protos.hyperparams_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='object_detection/protos/class_predictor.proto',
  package='object_detection.protos',
  serialized_pb=_b('\n-object_detection/protos/class_predictor.proto\x12\x17object_detection.protos\x1a)object_detection/protos/hyperparams.proto\"\xa7\x01\n\x0e\x43lassPredictor\x12|\n.multi_task_label_convolutional_class_predictor\x18\x01 \x01(\x0b\x32\x42.object_detection.protos.MultiTaskLabelConvolutionalClassPredictorH\x00\x42\x17\n\x15\x63lass_predictor_oneof\"\xbc\x02\n)MultiTaskLabelConvolutionalClassPredictor\x12>\n\x10\x63onv_hyperparams\x18\x01 \x01(\x0b\x32$.object_detection.protos.Hyperparams\x12&\n\x1bnum_layers_before_predictor\x18\x04 \x01(\x05:\x01\x30\x12\x19\n\x0buse_dropout\x18\x05 \x01(\x08:\x04true\x12%\n\x18\x64ropout_keep_probability\x18\x06 \x01(\x02:\x03\x30.8\x12\x16\n\x0bkernel_size\x18\x07 \x01(\x05:\x01\x31\x12&\n\x17\x61pply_sigmoid_to_scores\x18\t \x01(\x08:\x05\x66\x61lse\x12%\n\x1a\x63lass_prediction_bias_init\x18\n \x01(\x02:\x01\x30')
  ,
  dependencies=[object_detection.protos.hyperparams_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CLASSPREDICTOR = _descriptor.Descriptor(
  name='ClassPredictor',
  full_name='object_detection.protos.ClassPredictor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='multi_task_label_convolutional_class_predictor', full_name='object_detection.protos.ClassPredictor.multi_task_label_convolutional_class_predictor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='class_predictor_oneof', full_name='object_detection.protos.ClassPredictor.class_predictor_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=118,
  serialized_end=285,
)


_MULTITASKLABELCONVOLUTIONALCLASSPREDICTOR = _descriptor.Descriptor(
  name='MultiTaskLabelConvolutionalClassPredictor',
  full_name='object_detection.protos.MultiTaskLabelConvolutionalClassPredictor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conv_hyperparams', full_name='object_detection.protos.MultiTaskLabelConvolutionalClassPredictor.conv_hyperparams', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_layers_before_predictor', full_name='object_detection.protos.MultiTaskLabelConvolutionalClassPredictor.num_layers_before_predictor', index=1,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_dropout', full_name='object_detection.protos.MultiTaskLabelConvolutionalClassPredictor.use_dropout', index=2,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dropout_keep_probability', full_name='object_detection.protos.MultiTaskLabelConvolutionalClassPredictor.dropout_keep_probability', index=3,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0.8,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kernel_size', full_name='object_detection.protos.MultiTaskLabelConvolutionalClassPredictor.kernel_size', index=4,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='apply_sigmoid_to_scores', full_name='object_detection.protos.MultiTaskLabelConvolutionalClassPredictor.apply_sigmoid_to_scores', index=5,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='class_prediction_bias_init', full_name='object_detection.protos.MultiTaskLabelConvolutionalClassPredictor.class_prediction_bias_init', index=6,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=604,
)

_CLASSPREDICTOR.fields_by_name['multi_task_label_convolutional_class_predictor'].message_type = _MULTITASKLABELCONVOLUTIONALCLASSPREDICTOR
_CLASSPREDICTOR.oneofs_by_name['class_predictor_oneof'].fields.append(
  _CLASSPREDICTOR.fields_by_name['multi_task_label_convolutional_class_predictor'])
_CLASSPREDICTOR.fields_by_name['multi_task_label_convolutional_class_predictor'].containing_oneof = _CLASSPREDICTOR.oneofs_by_name['class_predictor_oneof']
_MULTITASKLABELCONVOLUTIONALCLASSPREDICTOR.fields_by_name['conv_hyperparams'].message_type = object_detection.protos.hyperparams_pb2._HYPERPARAMS
DESCRIPTOR.message_types_by_name['ClassPredictor'] = _CLASSPREDICTOR
DESCRIPTOR.message_types_by_name['MultiTaskLabelConvolutionalClassPredictor'] = _MULTITASKLABELCONVOLUTIONALCLASSPREDICTOR

ClassPredictor = _reflection.GeneratedProtocolMessageType('ClassPredictor', (_message.Message,), dict(
  DESCRIPTOR = _CLASSPREDICTOR,
  __module__ = 'object_detection.protos.class_predictor_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.ClassPredictor)
  ))
_sym_db.RegisterMessage(ClassPredictor)

MultiTaskLabelConvolutionalClassPredictor = _reflection.GeneratedProtocolMessageType('MultiTaskLabelConvolutionalClassPredictor', (_message.Message,), dict(
  DESCRIPTOR = _MULTITASKLABELCONVOLUTIONALCLASSPREDICTOR,
  __module__ = 'object_detection.protos.class_predictor_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.MultiTaskLabelConvolutionalClassPredictor)
  ))
_sym_db.RegisterMessage(MultiTaskLabelConvolutionalClassPredictor)


# @@protoc_insertion_point(module_scope)
