# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_detection/protos/multi_task_label.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='object_detection/protos/multi_task_label.proto',
  package='',
  serialized_pb=_b('\n.object_detection/protos/multi_task_label.proto\"3\n\x0eMultiTaskLabel\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0bnum_classes\x18\x02 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MULTITASKLABEL = _descriptor.Descriptor(
  name='MultiTaskLabel',
  full_name='MultiTaskLabel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MultiTaskLabel.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_classes', full_name='MultiTaskLabel.num_classes', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['MultiTaskLabel'] = _MULTITASKLABEL

MultiTaskLabel = _reflection.GeneratedProtocolMessageType('MultiTaskLabel', (_message.Message,), dict(
  DESCRIPTOR = _MULTITASKLABEL,
  __module__ = 'object_detection.protos.multi_task_label_pb2'
  # @@protoc_insertion_point(class_scope:MultiTaskLabel)
  ))
_sym_db.RegisterMessage(MultiTaskLabel)


# @@protoc_insertion_point(module_scope)
